# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: b9e57e888956b21b85e0608cce12b6058acf464e8fbda0174271aeb7ccfda105432f2af707ee1f02681f91623846c70d99f3a0406b58b69006d3483ffeeb49f6
  smmry_api_key: 82E88325A1

test:
  domain_name: example.com 
  secret_key_base: 557c78915106bb46001c2df72c98cd2b993bbd2d28768deabdb2938913cc9fde16cfe416a14d9370dd02bd97ea7c347801dc22a43f62716cbf0b757053193caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smmry_api_key: 82E88325A1
